config/routes.rb
Rails.application.routes.draw do
  
  get 'calls' => "calls#root", as: :calls
  resources :calls, only: :create
  mount ActionCable.server, at: '/cable'

  resources :covid_conditions
  resources :prescriptions do
  post 'reenviar' => "prescriptions#reenviar", as: :reenviar
  end

  resources :consults do
      resources :answers, only: [:create, :destroy, :update]
      put 'mandar'
  end

  resources :bills do
  post 'reenviar' => "bills#reenviar", as: :reenviar
  end
  
  resources :profile, only: :show
  resources :services, only: [:index, :new, :create, :destroy]
  resources :dservices, only: [:index, :new, :create, :destroy]

  devise_for :patients, path: 'patients', controllers: {
    sessions: "patients/sessions",
    passwords: "patients/passwords",
    registrations: "patients/registrations",
    confirmations: "patients/confirmations" }

  devise_for :doctors, path: 'doctors', controllers: {
    sessions: "doctors/sessions",
    passwords: "doctors/passwords",
    registrations: "doctors/registrations",
    confirmations: "doctors/confirmations" }

    resources :stores do
      post 'show' => "stores#show", as: :show
    end

  root 'welcome#index'

  get 'welcome/closed'
  get 'welcome/search'
  get 'welcome/recipe'
  
  post 'cart' => "stores#cart"
  get 'cart' => "stores#cart"
  post 'shipping' => "stores#shipping"
  get 'shipping' => "stores#shipping"
  post 'saveship' => "stores#saveship"
  post 'payment' => "stores#payment"
  get 'payment' => "stores#payment"
  post 'savepay' => "stores#savepay"
  post 'sell' => "stores#sell"
  get 'sell' => "stores#sell"
  post 'savesell' => "stores#savesell"
  delete 'cart' => "stores#quitaritem", as: :delete

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/prescription.rb
class Prescription < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
  belongs_to :consult_type

  after_create :send_mail

  scope :ultimos, -> { order("created_at DESC")}
  # Ex:- scope :active, -> {where(:active => true)}

  def send_mail
    AnswerMailer.new_prescription(self).deliver!
  end

end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
  before_action :set_prescription, only: [:show, :edit, :update, :destroy]

  def reenviar
    @prescription = Prescription.find(params[:prescription_id])
    AnswerMailer.new_prescription(@prescription).deliver!
    flash[:notice] = "Receta reenviada."
    redirect_to prescriptions_path
  end

  # GET /prescriptions
  # GET /prescriptions.json
  def index
    if doctor_signed_in?
      @prescriptions = Prescription.paginate(page: params[:page], per_page:5).where(doctor: current_doctor).ultimos
    else
      if patient_signed_in?
        @prescriptions = Prescription.paginate(page: params[:page], per_page:5).where(patient: current_patient).ultimos
      else
        redirect_to root_path
      end
    end
  end

  # GET /prescriptions/1
  # GET /prescriptions/1.json
  def show
    respond_to do |format|
      format.html
      format.json
      format.pdf { render template: 'prescriptions/receta', pdf:'Receta', layout: 'pdf.html'}
    end
  end

  # GET /prescriptions/new
  def new
    if doctor_signed_in?
      @prescription = Prescription.new
    else
      redirect_to root_path
    end
  end

  # GET /prescriptions/1/edit
  def edit
    if !doctor_signed_in?
      redirect_to root_path
    end
  end

  # POST /prescriptions
  # POST /prescriptions.json
  def create
    @prescription = Prescription.new(prescription_params)

    respond_to do |format|
      if @prescription.save
        format.html { redirect_to @prescription, notice: 'Prescription was successfully created.' }
        format.json { render :show, status: :created, location: @prescription }
      else
        format.html { render :new }
        format.json { render json: @prescription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prescriptions/1
  # PATCH/PUT /prescriptions/1.json
  def update
    respond_to do |format|
      if @prescription.update(prescription_params)
        format.html { redirect_to @prescription, notice: 'Prescription was successfully updated.' }
        format.json { render :show, status: :ok, location: @prescription }
      else
        format.html { render :edit }
        format.json { render json: @prescription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prescriptions/1
  # DELETE /prescriptions/1.json
  def destroy
    @prescription.destroy
    respond_to do |format|
      format.html { redirect_to prescriptions_url, notice: 'Prescription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prescription
      @prescription = Prescription.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def prescription_params
      params.require(:prescription).permit(:patient_id, :consult_type_id, :subject, :body).merge(doctor_id: current_doctor.id)
    end
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/views/prescriptions/_form.html.erb
<div class="Prescripcion">
<%= form_with(model: prescription, local: true) do |form| %>
  <% if prescription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prescription.errors.count, "error") %> prohibited this prescription from being saved:</h2>

      <ul>
      <% prescription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="col-sm-5 field">
    <%= form.label :paciente %>
    <%= form.select :patient_id, options_from_collection_for_select(Patient.all, :id,:name)%>
  </div>
  <div class="col-sm-5 field">
    <%= form.label :Tipo_de_consulta %>
    <%= form.select :consult_type_id, options_from_collection_for_select(ConsultType.all, :id,:name)%>
  </div>
</div>
<div class="row">
  <div class="col-sm-9 field">
    <%= form.label :Diagnostico %>
    <%= form.text_field :subject %>
  </div>
</div>
<div class="row">
  <div class="col-sm-11 field">
    <%= form.label :Receta %>
    <%= form.text_area :body, :cols => 53, :rows => 3 %>
  </div>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/prescriptions/_see.html.erb
<%if @prescriptions != []%>
<table>
<thead>
<tr>
<%if doctor_signed_in?%>
<th>Paciente</th>
<%else%>
<th>Doctor</th>
<%end%>
<th>Tipo de consulta</th>
<th>Diagnóstico</th>
<th>Fecha de creación</th>
<th colspan="3"></th>
</tr>
</thead>

<tbody>
<% @prescriptions.each do |prescription| %>
<tr>
<%if doctor_signed_in?%>
<td class="text-center"><a href= <%=profile_path(prescription.patient.username)%>>
    <%= prescription.patient.name %> <%= prescription.patient.lastname %>
</td>
<%else%>
<td class="text-center"><a href= <%=profile_path(prescription.doctor.username)%>>
    <%= prescription.doctor.name %> <%= prescription.doctor.lastname %>
</td>
<%end%> 
<td class="text-center"><%= prescription.consult_type.name %></td>
<td><%= prescription.subject %></td>
<td><%= prescription.created_at %></td>
<td><%= button_to 'Imprimir', prescription_path(prescription, :format => :pdf), method: :get  %></td>
<%if doctor_signed_in?%>
<td><%= button_to "Reenviar", prescription_reenviar_path(:prescription_id => prescription.id), data: { confirm: 'Seguro de reenviar la factura?' }%></td>
<td><%= button_to 'Eliminar', prescription, method: :delete, data: { confirm: 'Esta seguro?' } %></td>
<%end%>
</tr>
<% end %>
</tbody>
</table>
<%end%>

app/views/prescriptions/edit.html.erb
<h1>Editing Prescription</h1>

<%= render 'form', prescription: @prescription %>

<%= link_to 'Show', @prescription %> |
<%= link_to 'Back', prescriptions_path %>

app/views/prescriptions/index.html.erb
<div class="shadow">
  <p id="notice"><%= notice %></p>

  <h1>Recetas</h1>
  <div class="digg_pagination">
    <%= will_paginate @prescriptions, :container => false %>
  </div>
  <%=render "see"%>
  <%if doctor_signed_in? %>
  <%= button_to 'Nueva Receta', new_prescription_path,  method: :get %>
  <br>
  <%end%>
</div>

app/views/prescriptions/new.html.erb
<div class="shadow">
    <h1>Nueva Receta</h1>

    <%= render 'form', prescription: @prescription %>

</div>

app/views/prescriptions/receta.pdf.erb
<h1 class="text-center">RubyHealthCare</h1>

<div style="position: absolute; padding-left: 5%;">
    <p><%=@prescription.doctor.address%></p>
    <p><%=@prescription.doctor.city%>, <%=@prescription.doctor.state+"."%></p>
    <p><%=@prescription.doctor.cellphone%></p>
</div>
<div style="position: absolute; padding-top: 12%; padding-left: 30%;">
    <h2><%=@prescription.doctor.name%><%=@prescription.doctor.lastname%></h2>
    <p>Especialidad: <%=@prescription.doctor.speciality.name%></p>
    <p><%=@prescription.doctor.license%></p>
</div>    
<div style="position: absolute; padding-top: 30%; text-align: center;">
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
</div>
<div style="position:absolute; padding-top: 30%;padding-left: 30px;">
    <p>Paciente:<%=@prescription.patient.name + " " + @prescription.patient.lastname%></p>
    <p><%=@prescription.patient.address%></p>
    <p><%=@prescription.patient.city+", "+@prescription.patient.state+"."%></p>
</div>
<div style="position:absolute; padding-top: 30%; padding-left: 65%;">
    <p>Edad: <%=Time.now.year - @prescription.patient.birth.year%> años</p>
    <p>Teléfono: <%=@prescription.patient.cellphone%></p>
</div>
<div style="position:absolute; padding-top: 50%; padding-left: 25%;">
    <h3>Rp/</h3>
    <p><%=@prescription.body%></p>
    <p>Diagnostico: <%=@prescription.subject%></p>
</div>
<div style="position:absolute; padding-top: 65%; padding-left: 15%;">
    <p>Fecha: <%=@prescription.created_at%></p>
</div>

app/views/prescriptions/show.html.erb
 <div class="shadow">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Paciente:</strong>
    <%= @prescription.patient.name %> <%= @prescription.patient.lastname %>
  </p>

  <p>
    <strong>Tipo de receta:</strong>
    <%= @prescription.consult_type.name %>
  </p>
  <p>
    <strong>Fecha de creacion:</strong>
    <%= @prescription.created_at %>
  </p>
  <p>
    <strong>Diagnóstico:</strong>
    <%= @prescription.subject %>
  </p>


  <p>
    <strong>Receta:</strong>
    <%= @prescription.body %>
  </p>

  <%= link_to 'Edit', edit_prescription_path(@prescription) %> |
  <%= link_to 'Back', prescriptions_path %>
</div>