config/routes.rb
Rails.application.routes.draw do
  
  get 'calls' => "calls#root", as: :calls
  resources :calls, only: :create
  mount ActionCable.server, at: '/cable'

  resources :covid_conditions
  resources :prescriptions do
  post 'reenviar' => "prescriptions#reenviar", as: :reenviar
  end

  resources :consults do
      resources :answers, only: [:create, :destroy, :update]
      put 'mandar'
  end

  resources :bills do
  post 'reenviar' => "bills#reenviar", as: :reenviar
  end
  
  resources :profile, only: :show
  resources :services, only: [:index, :new, :create, :destroy]
  resources :dservices, only: [:index, :new, :create, :destroy]

  devise_for :patients, path: 'patients', controllers: {
    sessions: "patients/sessions",
    passwords: "patients/passwords",
    registrations: "patients/registrations",
    confirmations: "patients/confirmations" }

  devise_for :doctors, path: 'doctors', controllers: {
    sessions: "doctors/sessions",
    passwords: "doctors/passwords",
    registrations: "doctors/registrations",
    confirmations: "doctors/confirmations" }

    resources :stores do
      post 'show' => "stores#show", as: :show
    end

  root 'welcome#index'

  get 'welcome/closed'
  get 'welcome/search'
  get 'welcome/recipe'
  
  post 'cart' => "stores#cart"
  get 'cart' => "stores#cart"
  post 'shipping' => "stores#shipping"
  get 'shipping' => "stores#shipping"
  post 'saveship' => "stores#saveship"
  post 'payment' => "stores#payment"
  get 'payment' => "stores#payment"
  post 'savepay' => "stores#savepay"
  post 'sell' => "stores#sell"
  get 'sell' => "stores#sell"
  post 'savesell' => "stores#savesell"
  delete 'cart' => "stores#quitaritem", as: :delete

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :medicament
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_cart, only: [:show, :cart, :sell]
  before_action :set_shipping, only: [:sell, :shipping, :saveship, :savesell]
  before_action :set_payment, only: [:sell, :payment, :savepay, :savesell]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Medicament.paginate(page: params[:page], per_page:5).all
  end

  def show
    @product = Medicament.find_by(id: store_params[:medicament_id])
    @carro = Cart.find_by(patient: current_patient)
    if CartDetail.find_by(cart: @carro, medicament: @product)
      insertar= CartDetail.find_by(cart: @carro, medicament: @product)
    else
      insertar= CartDetail.new
    end
    insertar.cart = Cart.find_by(patient: current_patient)
    insertar.medicament = @product
    if store_params[:quantity] != nil && store_params[:quantity] > "0"
      insertar.quantity = store_params[:quantity]
      if insertar.save
        flash[:notice] = "Agregado al carrito."
        redirect_to stores_path
      end
    else
      flash[:notice] = "El producto debe ser mayor a 0."
      redirect_to stores_path
    end
  end

  def cart
    @carrito = CartDetail.where(cart: @cart)
  end

  def shipping
    if CartDetail.find_by(cart: @cart) != nil
      redirect_to root_path
    end
  end

  def saveship
    if @envio.update(ship_params)
      redirect_to payment_path
    end
  end

  def payment
    if CartDetail.find_by(cart: @cart) != nil
      redirect_to root_path
    end
  end

  def savepay
    if @pago.update(pay_params)
      redirect_to sell_path
    end
  end

  def sell
    if !CartDetail.find_by(cart: @cart)
      redirect_to root_path
    end
    @carrito = CartDetail.where(cart: @cart)
  end

  def savesell
    @cart = Cart.find_by(patient: current_patient)
    @carrito = CartDetail.where(cart: @cart)
    @total = 222
    @carrito.each do |cart|
      @total = @total + (cart.medicament.price) * (cart.quantity)
    end
    @cart = Cart.find_by(patient: current_patient)
    @sell = Sell.new
    @sell.patient = @cart.patient
    @sell.shipping = @envio
    @sell.payment = @pago
    @sell.total = @total
    if @sell.save
      @carrito.each do |cart|
        @selld = SellDetail.new
        @selld.sell = @sell
        @selld.medicament = cart.medicament
        @selld.quantity = cart.quantity
        @selld.save
      end
      @carrito.each do |cart|
        cart.destroy
      end
      @cart.destroy
      flash[:notice] = "Su compra se realizo correctamente, gracias."
      redirect_to root_path
    end
  end

  def quitaritem
    carrito = CartDetail.find(params[:cart])
    carrito.destroy
    respond_to do |format|
      format.html { redirect_to cart_path, notice: 'El objeto se elimino del carrito', method: :post }
      format.json { head :no_content }
    end
  end

  private
  def set_cart
    if !patient_signed_in?
      redirect_to root_path
    end
    if Cart.find_by(patient: current_patient)
      @cart = Cart.find_by(patient: current_patient)
    else
      @cart = Cart.new
      @cart.patient = current_patient
      @cart.save
    end
  end
  private
  def set_shipping
    @envio = Shipping.find_by(patient: current_patient)
    if @envio == nil
      @envio = Shipping.new
      @envio.patient = current_patient
      @envio.save
    end
  end
  private
  def set_payment
    @pago = Payment.find_by(patient: current_patient)
    if @pago == nil
      @pago = Payment.new
      @pago.patient = current_patient
      @pago.save
    end
  end

    # Only allow a list of trusted parameters through.
    def store_params
      params.require(:algo).permit(:medicament_id, :quantity)
    end
    def ship_params
      params.require(:algo).permit(:name,:lastname,:city, :state, :country, :postal_code, :detail)
    end
    def pay_params
      params.require(:algo).permit(:name,:lastname,:number, :secret_code, :exdate)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store, local: true) do |form| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :medicament_id %>
    <%= form.text_field :medicament_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stores/cart.html.erb
<div class="shadow">
<h1>Carrito</h1>
<%if @carrito != [] %>
    <table>
    <thead>
        <tr>
        <th>Producto</th>
        <th>Precio</th>
        <th>Cantidad</th>
        <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @carrito.each do |cart| %>
        <tr>
            <td class="text-center"> <%= cart.medicament.name %> </td>
            <td class="text-center"> <%= cart.medicament.price %> </td>
            <td class="text-center"> <%= cart.quantity %> </td>
            <td><%= button_to 'Eliminar', cart_path(cart: cart), method: :delete, data: { confirm: 'Esta seguro?' } %></td>
        </tr>
        <% end %>
    </tbody>
    </table>
    <%=button_to "Pagar", shipping_path %>
<%end%>
</div>

app/views/stores/checkout.html.erb
<div class="shadow">

<p>
  <strong>Medicament:</strong>
  <%= @store.medicament %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>
</div>

app/views/stores/index.html.erb
<div class="shadow">

<h1>Tienda</h1>
<% if Cart.find_by(patient: current_patient)%>
  <%@carrito = CartDetail.where(:cart => Cart.where(patient: current_patient)) %>
  <h3>Articulos en el carrito: <%= @carrito.count%></h3> 
  <%if @carrito.count > 0%>
    <%=button_to "Carrito", cart_path %>
  <%end%>
<%end%>
<table>
  <thead>
    <tr>
      <th>Producto</th>
      <th>Compuesto Activo</th>
      <th>Presentación</th>
      <th>Precio</th>
      <th>Cantidad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr >
        <td class="text-center"> <%= store.name %> </td>
        <td class="text-center"> <%= store.active %> </td>
        <td class="text-center"> <%= store.presentation %> </td>
        <td class="text-center"> <%= store.price %> </td>
        <%= form_for :algo, method: :post, url: store_show_path(:store_id => store.id) do |f| %>
          <td><%=f.number_field :quantity%></td>
          <%=f.hidden_field :medicament_id, :value => store.id %>
          <td><%= f.submit 'Agregar'%></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="digg_pagination">
    <%= will_paginate @stores, :container => false %>
</div>

<br>
</div>

app/views/stores/payment.html.erb
<div class="shadow">
<h1>Información de pago</h1>
<div class="update">
    <%= form_for :algo, method: :post, url: savepay_path do |form| %>
        <div class="row">
            <div class="col-md-5">
                <div class="field">
                    <%= form.label :Nombre %>
                    <%= form.text_field :name, value: @pago.name %>
                </div> 
            </div>
            <div class="col-md-5">
                <div class="field">
                    <%= form.label :Apellido %>
                    <%= form.text_field :lastname, value:  @pago.lastname%>
                </div> 
            </div>
        </div>
        <div class="row">
            <div class="col-md-5">
                <div class="field">
                    <%= form.label :Numero %>
                    <%= form.number_field :number, value:  @pago.number%>
                </div>
            </div>
            <div class="col-md-5">
                <div class="field">
                    <%= form.label :Numero_secreto %>
                    <%= form.text_field :secret_code, value:  @pago.secret_code%>
                </div> 
            </div>
        </div>
        <div class="row">
            <div class="col-md-5">
                <div class="field">
                    <%= form.label :Fecha_de_expiración %>
                    <%= form.text_field :exdate, value: @pago.exdate %>
                </div> 
            </div>
        </div>  
        <div class="row">
            <div class="col-md-10"> 
                <%= form.submit 'Proceder a pagar'%>
            </div>
        </div>    
    </div>
<%end%>

</div>
</div>

app/views/stores/sell.html.erb
<div class="shadow">
<h1>Completar compra</h1>
<div>
    <h3><strong>Datos de envío</strong></h3>
    <div class ="row" style=" border-style: solid; display: inline-block;">
        <h3>&nbsp;&nbsp;&nbsp; Medicamentos &nbsp;&nbsp;&nbsp;</h3>
        <ul>
            <%@total = 0%>
            <% @carrito.each do |cart| %>
                <li><%=cart.medicament.name%> - $<%=cart.medicament.price%> - <%=cart.quantity%> unidades</li>
                <%@total = @total + cart.medicament.price * cart.quantity%>
            <%end%>
        </ul>
        <h3>&nbsp;&nbsp;&nbsp; Dirección de envio &nbsp;&nbsp;&nbsp;</h3>
        <ul>
            <li>Quién recibe: <%= @envio.name%> <%= @envio.lastname%></li>
            <li>Dirección: <%= @envio.detail%>, <%= @envio.city%>, <%= @envio.state%>, <%= @envio.country%>. &nbsp;&nbsp;</li>
            <li>Código Postal: <%= @envio.postal_code%></li>
        </ul>
        <h3>&nbsp;&nbsp;&nbsp; Información de pago &nbsp;&nbsp;&nbsp;</h3>
        <ul>
            <li>Nombre: <%=@pago.name%> <%=@pago.lastname%></li>
            <li>Número de tarjeta:<strong> <%=@pago.number%></strong></li>
            <li>Fecha de caducidad: <%=@pago.exdate%></li>
        </ul>
        <h3>&nbsp;&nbsp;&nbsp; Total &nbsp;&nbsp;&nbsp;</h3>
        <h3><strong><%= @total %></strong><h3>
        <%=button_to "Realizar Compra", savesell_path, method: :post %>
        <p></p>
    </div>
    <p></p>
</div>


</div>

app/views/stores/shipping.html.erb
<div class="shadow">
<h1>Dirección de envio</h1>
<div class="update">
    <%= form_for :algo, method: :post, url: saveship_path do |form| %>
        <div class="row">
            <div class="col-md-5">
                <div class="field">
                    <%= form.label :Nombre %>
                    <%= form.text_field :name, value: @envio.name %>
                </div> 
            </div>
            <div class="col-md-5">
                <div class="field">
                    <%= form.label :Apellido %>
                    <%= form.text_field :lastname, value:  @envio.lastname%>
                </div> 
            </div>
        </div>
        <div class="row">
            <div class="col-md-5">
                <div class="field">
                    <%= form.label :Ciudad %>
                    <%= form.text_field :city, value:  @envio.city%>
                </div>
            </div>
            <div class="col-md-5">
                <div class="field">
                    <%= form.label :Estado %>
                    <%= form.text_field :state, value:  @envio.state%>
                </div> 
            </div>
        </div>
        <div class="row">
            <div class="col-md-5">
                <div class="field">
                    <%= form.label :Pais %>
                    <%= form.text_field :country, value: @envio.country %>
                </div> 
            </div>
            <div class="col-md-5">
                <div class="field">
                    <%= form.label :Codigo_Postal %>
                    <%= form.text_field :postal_code, value: @envio.postal_code %>
                </div>
            </div>  
        </div>  
        <div class="row">
            <div class="col-md-10"> 
                <div class="field">
                    <%= form.label :Dirección %>
                    <%= form.text_field :detail, value: @envio.detail %>
                </div>
            </div>
        </div>  
        <div class="row">
            <div class="col-md-10"> 
                <%= form.submit 'Continuar'%>
            </div>
        </div>    
    </div>
<%end%>

</div>