config/routes.rb
Rails.application.routes.draw do
  
  get 'calls' => "calls#root", as: :calls
  resources :calls, only: :create
  mount ActionCable.server, at: '/cable'

  resources :covid_conditions
  resources :prescriptions do
  post 'reenviar' => "prescriptions#reenviar", as: :reenviar
  end

  resources :consults do
      resources :answers, only: [:create, :destroy, :update]
      put 'mandar'
  end

  resources :bills do
  post 'reenviar' => "bills#reenviar", as: :reenviar
  end
  
  resources :profile, only: :show
  resources :services, only: [:index, :new, :create, :destroy]
  resources :dservices, only: [:index, :new, :create, :destroy]

  devise_for :patients, path: 'patients', controllers: {
    sessions: "patients/sessions",
    passwords: "patients/passwords",
    registrations: "patients/registrations",
    confirmations: "patients/confirmations" }

  devise_for :doctors, path: 'doctors', controllers: {
    sessions: "doctors/sessions",
    passwords: "doctors/passwords",
    registrations: "doctors/registrations",
    confirmations: "doctors/confirmations" }

    resources :stores do
      post 'show' => "stores#show", as: :show
    end

  root 'welcome#index'

  get 'welcome/closed'
  get 'welcome/search'
  get 'welcome/recipe'
  
  post 'cart' => "stores#cart"
  get 'cart' => "stores#cart"
  post 'shipping' => "stores#shipping"
  get 'shipping' => "stores#shipping"
  post 'saveship' => "stores#saveship"
  post 'payment' => "stores#payment"
  get 'payment' => "stores#payment"
  post 'savepay' => "stores#savepay"
  post 'sell' => "stores#sell"
  get 'sell' => "stores#sell"
  post 'savesell' => "stores#savesell"
  delete 'cart' => "stores#quitaritem", as: :delete

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :consult
  belongs_to :doctor

  after_create :send_mail

  def send_mail
    AnswerMailer.new_answer(self).deliver!
  end
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
  
  after_create :send_mail

  scope :ultimos, -> { order("created_at DESC")}
  # Ex:- scope :active, -> {where(:active => true)}

  def send_mail
    AnswerMailer.new_bill(self).deliver!
  end

end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :patient

  has_many :cart_detail
end

app/models/cart_detail.rb
class CartDetail < ApplicationRecord
  belongs_to :cart
  belongs_to :medicament

end

app/models/condition.rb
class Condition < ApplicationRecord
end

app/models/consult.rb
class Consult < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
  belongs_to :speciality
  has_many_attached :adj
  has_many :answer

  validates :symptoms, presence: true, length: { minimum: 10}
  validate :adj_type

  scope :respondida, -> { where(:answered => 1)}
  # Ex:- scope :active, -> {where(:active => true)}
  scope :norespondida, -> { where(:answered => 0)}
  # Ex:- scope :active, -> {where(:active => true)}
  scope :cerrada, -> { where(:closed => 1)}
  # Ex:- scope :active, -> {where(:active => true)}
  scope :abierta, -> { where(:closed => 0)}
  # Ex:- scope :active, -> {where(:active => true)}
  scope :ultimos, -> { order("updated_at DESC")}
  # Ex:- scope :active, -> {where(:active => true)}

  def thumbnail input
    return self.adj[input].variant(resize: '500x300!').processed
  end
  private
  def adj_type
    if adj.attached? == false
      errors.add(:adj, "are missing!")
    end
    adj.each do |image|
      if !image.content_type.in?(%('image/jpg image/jpeg image/png video/mp4 video/webm')) 
        errors.add(:adj, "solo se reciben archivos jpg, jpeg, png, mp4 o webm")
      end
    end
  end
end

app/models/consult_type.rb
class ConsultType < ApplicationRecord
    has_many :prescription
end

app/models/d_service.rb
class DService < ApplicationRecord
  belongs_to :service
  belongs_to :doctor
  validates :service, uniqueness: { scope: :doctor }
  validates :price, presence: true, length: { minimum: 3}
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable,:confirmable
  validates :email, uniqueness: true
  validates :username, presence: true, uniqueness: true
  has_one_attached :avatar
  has_many :answers
  has_many :prescription
  belongs_to :speciality
end

app/models/medicament.rb
class Medicament < ApplicationRecord
  belongs_to :type_medication
  
  has_many :sell_detail
  has_many :cart_detail  
end

app/models/patient.rb
class Patient < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable,:confirmable
  validates :email, uniqueness: true
  validates :username, presence: true, uniqueness: true
  has_one_attached :avatar
  has_many :prescription
  has_many :sell

  after_create :insertarcovid

  geocoded_by :origin
  after_validation :geocode
  def insertarcovid
    @CovidCondition = CovidCondition.new
    @CovidCondition.patient = self
    @CovidCondition.condition = Condition.find(1)
    @CovidCondition.save
  end

  def origin
    [city, state, country].compact.join(', ')
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
    belongs_to :patient
    has_many :sell
end

app/models/prescription.rb
class Prescription < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
  belongs_to :consult_type

  after_create :send_mail

  scope :ultimos, -> { order("created_at DESC")}
  # Ex:- scope :active, -> {where(:active => true)}

  def send_mail
    AnswerMailer.new_prescription(self).deliver!
  end

end

app/models/sell.rb
class Sell < ApplicationRecord
  belongs_to :patient
  belongs_to :shipping
  belongs_to :payment

  has_many :sell_detail
end

app/models/sell_detail.rb
class SellDetail < ApplicationRecord
  belongs_to :sell
  belongs_to :medicament
end

app/models/service.rb
class Service < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    validates :description, presence: true, length: { minimum: 10}
end

app/models/shipping.rb
class Shipping < ApplicationRecord
    belongs_to :patient
    has_many :sell
end

app/models/speciality.rb
class Speciality < ApplicationRecord
    has_many :doctor
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :medicament
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if doctor_signed_in?
      @consults = Consult.paginate(page: params[:page], per_page:5).where(doctor: current_doctor).abierta
    else
      if patient_signed_in?
        @consults = Consult.paginate(page: params[:page], per_page:5).where(patient: current_patient).respondida.ultimos
      end 
    end
  end
  def closed
    if doctor_signed_in?
      @consults = Consult.paginate(page: params[:page], per_page:5).where(doctor: current_doctor).cerrada.ultimos
    end 
  end
  def search
    if doct = Doctor.where(speciality_id: search_params[:speciality_id])
      @search = DService.where(doctor: doct, service_id: search_params[:service_id])
    else
      @search = nil
    end
  end

  def show
  end
  def recipe
    @sell = Sell.paginate(page: params[:page], per_page:5).where(patient: current_patient)
    respond_to do |format|
      format.html
      format.json
      format.pdf { render template: 'welcome/recibo', pdf:'recibo', layout: 'pdf.html'}
    end
  end
  def search_params
    params.require(:algo).permit(:speciality_id,:service_id)
  end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/closed.html.erb
<%if doctor_signed_in? %>
    <div class = "shadow">
        <div class="digg_pagination">
            <%= will_paginate @consults, :container => false %>
        </div>
        <h2>Consultas Archivadas</h2>
        <%= render 'consults/see'%>
        <br>
    </div>
<%end%>

app/views/welcome/index.html.erb
<%if doctor_signed_in? %>
    <div class = "shadow">
        <h3>Bienvenido <%= current_doctor.name %></h3>
        <h2>Mis Consultas</h2>
        <%= render 'consults/see'%>
        <br>
        <div class="digg_pagination">
            <%= will_paginate @consults, :container => false %>
        </div>
    </div>
<%else%>
    <%if patient_signed_in? %>
        <div class = "shadow">
            <h3>Bienvenido <%= current_patient.name %></h3>
            <h2>Consultas Respondidas</h2>
            <div class="digg_pagination">
            <%= will_paginate @consults, :container => false %>
            </div>
            <%= render 'consults/see'%>
            <br>
        </div>
    <%else%>
        <div class="container">
            <div class="row text-center">
                <div class="col-sm-7">
                    <%=link_to image_tag("doctor.png", :size => "260x180", class: "img-circle center-block"), new_doctor_session_path%>
                </div>
                <div class="col-sm-1">
                    <%=link_to image_tag("patient.png", :size => "260x180", class: "img-circle center-block"), new_patient_session_path%>
                </div>
            </div>
            <p></p>
        </div>
    <%end%>
<%end%>

app/views/welcome/recibo.pdf.erb
<h1 class="text-center">RubyHealthCare</h1>

<h1>Completar compra</h1>
<div style="position: absolute; padding-top:5%;padding-left:30%;">
    <h3><strong>Datos de envío</strong></h3>
    <div class ="row" style=" border-style: solid; display: inline-block;">
        <h3>&nbsp;&nbsp;&nbsp; Medicamentos &nbsp;&nbsp;&nbsp;</h3>
        <ul>
            <%@total = 0%>
            <%@product = SellDetail.where(sell: @sell)%>
            <% @product.each do |cart| %>
                <li><%=cart.medicament.name%> - $<%=cart.medicament.price%> - <%=cart.quantity%> unidades</li>
                <%@total = @total + cart.medicament.price * cart.quantity%>
            <%end%>
        </ul>
        <h3>&nbsp;&nbsp;&nbsp; Dirección de envio &nbsp;&nbsp;&nbsp;</h3>
        <%@shipping = Sell.find_by(id: @sell).shipping%>
        <ul>
            <li>Quién recibe: <%= @shipping.name%> <%= @shipping.lastname%></li>
            <li>Dirección: <%= @shipping.detail%>, <%= @shipping.city%>, <%= @shipping.state%>, <%= @shipping.country%>. &nbsp;&nbsp;</li>
            <li>Código Postal: <%= @shipping.postal_code%></li>
        </ul>
        <h3>&nbsp;&nbsp;&nbsp; Información de pago &nbsp;&nbsp;&nbsp;</h3>
        <%@payment = Sell.find_by(id: @sell).payment%>
        <ul>
            <li>Nombre: <%=@payment.name%> <%=@payment.lastname%></li>
            <li>Número de tarjeta:<strong> <%=@payment.number%></strong></li>
            <li>Fecha de caducidad: <%=@payment.exdate%></li>
        </ul>
        <h3>&nbsp;&nbsp;&nbsp; Total &nbsp;&nbsp;&nbsp;</h3>
        <h3><strong><%= @total %></strong><h3>
        <p></p>
    </div>
    <p></p>
</div>


</div>

app/views/welcome/recipe.html.erb
<div class="shadow">
<p id="notice"><%= notice %></p>
<h1>Compras Realizadas</h1>
<%if @sell != [] %>
<div class="digg_pagination">
  <%= will_paginate @sell, :container => false %>
</div>
<table>
  <thead>
    <tr>
      <th style="width: 180px;">Fecha de compra</th>
      <th style="width: 100px;">Productos</th>
      <th style="width: 100px;">Cantidad</th>
      <th style="width: 50px;">SubTotal</th>
      <th style="width: 50px;">Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sell.each do |sell| %>
      <tr>
        <td><%= sell.created_at %></td>

        <%@product = SellDetail.where(sell: sell)%>
            <td class="text-center">
                <% @product.each do |prod| %>
                -><%= prod.medicament.name %><br>
                <%end%>
            </td>
            
            <td class="text-center">
                <% @product.each do |prod| %>
                -><%= prod.quantity %><br>
                <%end%>
            </td>
            <td class="text-center"><%= sell.total %></td>
            <td class="text-center"><%= sell.total + (sell.total* 0.16) %></td>
            <td><%= button_to 'Imprimir', welcome_recipe_path(sell: sell.id, :format => :pdf), method: :get  %></td>
       </tr>
    <% end %>
  </tbody>
</table>
<br>
<%end%>
<br>
</div>

app/views/welcome/search.html.erb
<div class="shadow">
<h3>Indique que desea buscar</h3>
    <%= form_for :algo, url: "search",method: :get do |f| %>
        <div style="display: inline-block;">
            <strong>Especialidad:</strong>
            <%=f.select :speciality_id, options_from_collection_for_select(Speciality.all, :id,:name)%>
            <strong>Servicio:</strong>
            <%=f.select :service_id, options_from_collection_for_select(Service.all, :id,:name)%>

            <%= f.submit 'Buscar' %>
        </div>
    <% end %>
    <br>
    <%if @search != [] %>
        <table>
            <thead>
            <tr>
                <th>Doctor</th>
                <th>Cédula</th>
                <th>Localidad</th>
            </tr>
            </thead>

            <tbody>
                <% @search.each do |search| %>
                    <%if search.doctor.name != "none" %>
                        <tr>
                            <td class="text-center"><a href= <%=profile_path(search.doctor.username)%>>
                                <%= search.doctor.name %> <%= search.doctor.lastname %>
                            </td>
                            <td class="text-center"><%= search.doctor.license %></td>
                            <td class="text-center">
                            <%= search.doctor.city %>, <%= search.doctor.state %>., <%= search.doctor.country %>.
                            </td>
                        </tr>
                    <%end%>
                <% end %>
            </tbody>
        </table>
    <%end%>
</div>