config/routes.rb
Rails.application.routes.draw do
  
  get 'calls' => "calls#root", as: :calls
  resources :calls, only: :create
  mount ActionCable.server, at: '/cable'

  resources :covid_conditions
  resources :prescriptions do
  post 'reenviar' => "prescriptions#reenviar", as: :reenviar
  end

  resources :consults do
      resources :answers, only: [:create, :destroy, :update]
      put 'mandar'
  end

  resources :bills do
  post 'reenviar' => "bills#reenviar", as: :reenviar
  end
  
  resources :profile, only: :show
  resources :services, only: [:index, :new, :create, :destroy]
  resources :dservices, only: [:index, :new, :create, :destroy]

  devise_for :patients, path: 'patients', controllers: {
    sessions: "patients/sessions",
    passwords: "patients/passwords",
    registrations: "patients/registrations",
    confirmations: "patients/confirmations" }

  devise_for :doctors, path: 'doctors', controllers: {
    sessions: "doctors/sessions",
    passwords: "doctors/passwords",
    registrations: "doctors/registrations",
    confirmations: "doctors/confirmations" }

    resources :stores do
      post 'show' => "stores#show", as: :show
    end

  root 'welcome#index'

  get 'welcome/closed'
  get 'welcome/search'
  get 'welcome/recipe'
  
  post 'cart' => "stores#cart"
  get 'cart' => "stores#cart"
  post 'shipping' => "stores#shipping"
  get 'shipping' => "stores#shipping"
  post 'saveship' => "stores#saveship"
  post 'payment' => "stores#payment"
  get 'payment' => "stores#payment"
  post 'savepay' => "stores#savepay"
  post 'sell' => "stores#sell"
  get 'sell' => "stores#sell"
  post 'savesell' => "stores#savesell"
  delete 'cart' => "stores#quitaritem", as: :delete

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
  
  after_create :send_mail

  scope :ultimos, -> { order("created_at DESC")}
  # Ex:- scope :active, -> {where(:active => true)}

  def send_mail
    AnswerMailer.new_bill(self).deliver!
  end

end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  def reenviar
    @bill = Bill.find(params[:bill_id])
    AnswerMailer.new_bill(@bill).deliver!
    flash[:notice] = "Factura reenviada."
    redirect_to bills_path
  end

  # GET /bills
  # GET /bills.json
  def index
    if doctor_signed_in?
      @bills = Bill.paginate(page: params[:page], per_page:5).where(doctor: current_doctor).ultimos
    else
      if patient_signed_in?
        @bills = Bill.paginate(page: params[:page], per_page:5).where(patient: current_patient).ultimos
      else
        redirect_to root_path
      end
    end
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
    respond_to do |format|
      format.html
      format.json
      format.pdf { render template: 'bills/factura', pdf:'Factura', layout: 'pdf.html'}
    end
  end

  # GET /bills/new
  def new
    if doctor_signed_in?
      @bill = Bill.new
    else
      redirect_to root_path
    end
  end

  # GET /bills/1/edit
  def edit
    if !doctor_signed_in?
      redirect_to root_path
    end
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bill_params
      params.require(:bill).permit(:patient_id, :body, :total).merge(doctor_id: current_doctor.id)
    end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_form.html.erb
<div class="bill">
<%= form_with(model: bill, local: true) do |form| %>
  <% if bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="col-sm-10 field">
    <%= form.label :Paciente %>
    <%= form.select :patient_id, options_from_collection_for_select(Patient.all, :id,:name)%>
  </div>
</div>
<div class="row">
  <div class="col-sm-10 field">
    <%= form.label :Concepto_de_facturación %>
    <%= form.text_area :body, :cols => 60, :rows => 3  %>
  </div>
</div>
<div class="row">
  <div class="col-sm-10 field">
    <%= form.label :Total %>
    <%= form.text_field :total %>
  </div>
  <div class="col-sm-10">
  <div class="actions">
    <%= form.submit %>
  </div>
  </div>
</div>
<% end %>
</div>

app/views/bills/edit.html.erb
<div class="shadow">
<h1>Editing Bill</h1>

<%= render 'form', bill: @bill %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>
</div>

app/views/bills/factura.pdf.erb
<h1 class="text-center">RubyHealthCare</h1>
<div style="position: absolute; padding-left: 30px;">
    <p><%=@bill.doctor.address%></p>
    <p><%=@bill.doctor.city+", "+@bill.doctor.state+"."%></p>
    <p><%=@bill.doctor.cellphone%></p>
</div>
    <p style="text-align:right;">FECHA: <%=@bill.created_at%></p>
<div style="position: absolute; padding-top: 10%; padding-left: 30px;">    
    <h3>FACTURAR A:</h3>
    <p><%=@bill.patient.name + " " + @bill.patient.lastname%></p>
    <p><%=@bill.patient.address%></p>
    <p><%=@bill.patient.city+", "+@bill.patient.state+"."%></p>
    <p><%=@bill.patient.cellphone%></p>
</div>
<div class="center" style="position: absolute; padding-top: 35%;">
    <table>
        <thead>
            <tr>
                <th style="width: 1000px;">Concepto</th>
                <th style="width: 20%;">Total</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><%=@bill.body%></td>
            </tr>
            <tr>
                <th>SubTotal :</th>
                <td>$ <%=@bill.total%></td>
            </tr>
            <tr>
                <th>Impuesto 16% :</th>
                <td>$ <%=(@bill.total * 0.16)%></td>
            </tr>
            <tr>
                <th>Total :</th>
                <td>$ <%=@bill.total+(@bill.total * 0.16)%></td>
            </tr>
        </tbody>
    </table>
</div>

app/views/bills/index.html.erb
<div class="shadow">
<p id="notice"><%= notice %></p>

<h1>Facturas</h1>
<%if @bills != [] %>
<div class="digg_pagination">
  <%= will_paginate @bills, :container => false %>
</div>
<table>
  <thead>
    <tr>
      <%if doctor_signed_in?%>
      <th>Paciente</th>
      <%else%>
      <th>Doctor</th>
      <%end%>
      <th style="width: 400px;">Servicios</th>
      <th style="width: 50px;">Total</th>
      <th>Fecha de creación</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <%if doctor_signed_in?%>
        <td class="text-center"><a href= <%=profile_path(bill.patient.username)%>>
          <%= bill.patient.name %> <%=bill.patient.lastname%>
        </td>
        <%else%>
        <td class="text-center"><a href= <%=profile_path(bill.doctor.username)%>>
          <%= bill.doctor.name %> <%=bill.doctor.lastname%>
        </td>
        <%end%>
        <td><%= bill.body %></td>
        <td class="text-center"><%= bill.total %></td>
        <td class="text-center"><%= bill.created_at %></td>
        <td><%= button_to 'Imprimir', bill_path(bill, :format => :pdf), method: :get  %></td>
        <%if doctor_signed_in?%>
          <td><%= button_to "Reenviar", bill_reenviar_path(:bill_id => bill.id),data: { confirm: 'Seguro de reenviar la factura?' }  %></td>
          <td><%= button_to 'Eliminar', bill, method: :delete, data: { confirm: 'Seguro de eliminar la factura?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%end%>
<%if doctor_signed_in?%>
  <%= button_to 'Nueva Factura', new_bill_path, method: :get%>
<%end%>
<br>
</div>

app/views/bills/new.html.erb
<div class="shadow">
<h1>Nueva Factura</h1>

<%= render 'form', bill: @bill %>
</div>

app/views/bills/show.html.erb
<div class="shadow">
<p id="notice"><%= notice %></p>

<p>
  <strong>Doctor:</strong>
  <%= @bill.doctor.name %> <%= @bill.doctor.lastname %>
</p>

<p>
  <strong>Paciente:</strong>
  <%= @bill.patient.name %> <%= @bill.patient.lastname %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @bill.body %>
</p>

<p>
  <strong>Total:</strong>
  <%= @bill.total %>
</p>

<%= link_to 'Edit', edit_bill_path(@bill) %> |
<%= link_to 'Back', bills_path %>
</div>